# Project information
site_name: Aiogram 2.Xda Telegram botlarni yozish
site_description: Aiogram 2.x bilan Pythonda Telegram botlarni ishlab chiqish boyicha qollanma
site_author: Groosha
site_url: https://metabrozzpy.github.io/aiogram-2-guide-uz
docs_dir: book_src
site_dir: docs

# Repository
repo_name: metabrozzpy/aiogram-2-guide-uz
repo_url: https://github.com/metabrozzpy/aiogram-2-guide-uz
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2022 Groosha

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: uz
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/TsftDfnevFLQS1ts
      name: "Чат в Telegram"
    - icon: fontawesome/brands/github-alt
      link: https://github.com/metabrozzpy/aiogram-2-guide-uz
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - meta
  - attr_list
  - toc:
      permalink: true

nav:
  - "Kirish": index.md
  - "Aiogram bilan tanishuv": quickstart.md
  - "Xabarlar bilan ishlash": messages.md
  - "Tugmalar": buttons.md
  - "FSM (Steytlar)": fsm.md
  - "Inlayn rejimi": inline_mode.md

plugins:
  - search:
      lang:
        - uz
        - en
        - ru

# Custom
nav_name: "Mundarija"
